name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Continuous Integration Build
    outputs:
      artifact: ${{ steps.artifact.outputs.artifact_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache Maven repository
        uses: actions/cache@v3.0.9
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build
        run: mvn -B -Drevision=$GITHUB_RUN_NUMBER verify
      - name: Extract Artifact Name
        run: |
          echo "ARTIFACT_NAME=$(mvn help:evaluate -Drevision=$GITHUB_RUN_NUMBER -Dexpression=project.build.finalName -q -DforceStdout).jar" >> $GITHUB_ENV
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: target/${{ env.ARTIFACT_NAME }}
      - name: Output Artifact Name
        id: artifact
        run: echo "::set-output name=artifact_name::$ARTIFACT_NAME"
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
      - shell: bash
        env:
          ARTIFACT_NAME: ${{ needs.build.outputs.artifact }}
        run: |
          echo "Artifact: $ARTIFACT_NAME"
          echo "${{ needs.build.outputs.artifact }}"
      - shell: bash
        env:
          FLINK_USERNAME: ${{ secrets.FLINKUSERNAME }}
          FLINK_PASSWORD: ${{ secrets.FLINKPASSWORD }}
        run: |
          curl -u "$FLINK_USERNAME:$FLINK_PASSWORD" -X POST -H "Expect:" -F "jarfile=@${{ needs.build.outputs.artifact }}" https://flink.schroeder.lol/jars/upload